name: build_docker

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master

      - name: Login to Docker Hub
        uses: docker/login-action@master
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@master
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/kairos
          tags: |
            type=sha

      - name: Build and push
        uses: docker/build-push-action@master
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            docker stop frenchclass
            docker rm frenchclass
            docker pull frenchclass:latest
            docker run --name frenchclass --memory=250m -P "3000:3000" --env-file=.env -d frenchclass
